services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9001:9001"
    volumes:
      - minio_data:/data
      - ./ssl:/root/.minio/certs
    command: server /data --console-address ":9001" --address ":9000"

  backend:
    image: ghcr.io/kukaracka/digitalpassportserver:latest
    env_file:
      - .env 
    depends_on:
      - db
      - minio
    volumes:
      # - ./src:/app/src
      - ./ssl:/app/ssl
    ports:
      - "8443:8443"
    command: [
      "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8443",
      "--ssl-keyfile", "/app/ssl/key.pem",
      "--ssl-certfile", "/app/ssl/cert.pem"
    ]

volumes:
  pgdata:
  minio_data:
