version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: digitalpassport
      POSTGRES_PASSWORD: digitalpassportpass
      POSTGRES_DB: digitalpassportdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://digitalpassport:digitalpassportpass@db:5432/digitalpassportdb
    volumes:
      - ./backend:/app
      - ./ssl:/app/ssl  # Монтируем папку с сертификатами
    ports:
      - "8443:8443"    # Меняем порт на HTTPS
    command: [
      "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8443",
      "--ssl-keyfile", "/app/ssl/key.pem", 
      "--ssl-certfile", "/app/ssl/cert.pem",
      "--reload"
    ]

volumes:
  pgdata:
